# Generated by Django 4.2.7 on 2023-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='next_task_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='previous_task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
