# Generated by Django 4.2.7 on 2023-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_next_task_id_alter_task_previous_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
