# Generated by Django 4.2.7 on 2023-11-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_id_alter_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
